### ISSUE TITLE
Is it possible to place Buy/Sell Forex Trades?

### ISSUE THREAD

**Issue by constiko** [MongkonEiadon/IqOption.Net#11]
Hello @MongkonEiadon, 
thanks first of all for this great repository. Is it possible to place Buy/Sell Forex Trades via this api? I have the problem that Binary Options aren´t allowed in the European Union anymore, and the BuyAsync method works only for Binary Options, as far as I know.
So would it be complex to implement a Forex Buy/Sell Method (or does it already exists?)
Thank you in advance!
Constantin Koch

**Comment by MongkonEiadon** [comment]
Thanks for your interesting, but for your question about open the forex position, not able with this API, because this Api would work with IqOption (See. https://iqoption.com) only, if you can trade with this website you can able to use this Api also : )

**Comment by constiko** [comment]
Thanks for your fast reply. I mean, I actually *can* trade forex positions via IqOption / [https://iqoption.com](https://iqoption.com), as shown in the attached picture.
![picture](https://user-images.githubusercontent.com/35102102/46474198-8ef8b380-c7e2-11e8-981a-bdbdb3d13bd8.png)
So is it possible to trade forex positions via this api, and if yes, how?
Thanks for your effort!
