### ISSUE TITLE
select practice or real account before open a order

### ISSUE THREAD

**Issue by excepticons** [MongkonEiadon/IqOption.Net#17]
How I can select practice or real account before open a order?

**Comment by MongkonEiadon** [comment]
you can call "ChangeBalance(int balanceId)"
the balance Id came from when you get profile here 

![image](https://user-images.githubusercontent.com/3174809/53928218-df3eaf00-40bb-11e9-9f12-02a7dd9a9ca1.png)

you can tried postman collection on develop brach
