### ISSUE TITLE
How to send data to API?

### ISSUE THREAD

**Issue by slangza** [MongkonEiadon/iqoption.net#3]
How do I send buy/sell orders through this API ?
It's started with a console window, login success

and whats the difference between this project and
https://github.com/MongkonEiadon/iqoption-follower ?

Thanks

**Comment by MongkonEiadon** [comment]
I've checked the code and fixing some thing you can check the file Startup.cs, so the open order is look like this

 ``
                // open order EurUsd in smallest period (1min) 
                var exp = DateTime.Now.AddMinutes(1);
                var buyResult = await api.BuyAsync(ActivePair.EURUSD, 1, OrderDirection.Call, exp);

**Comment by junghojun** [comment]
hello MongkonEiadon,

i hope know about the send data with this.

{"name":"buyV2","msg":{"price":1,"act":1,"exp":1534385525,"type":"turbo","direction":"call","time":1534385465}}

but some people told me like this.

{"name":"buyV2","msg":{"price":1,"act":1,"exp":1534385525,"type":"turbo","direction":"call","time":1534385465.05}}

but i don't know how to change of this...

**Comment by MongkonEiadon** [comment]
the time was int type, (unix time stamp) if you use this tool you will see the 'timesync' response every second,  that is a ipoption server time
![image](https://user-images.githubusercontent.com/3174809/44262173-44c46e80-a244-11e8-8d3d-48e14d9118ec.png)

That why this time used for flag the 'buyv2'

**Comment by junghojun** [comment]
i have change of the souce.

but the trading function is not work... i have checked times already.

so i have send of the data. like this.

exceptions : 2018-08-17 오후 2:41:00
hereDateTime : 2018-08-17 오후 2:40:41

{"name":"1627574","msg":{"price":1,"act":1,"exp":1534516860,"type":"turbo","direction":"call","time":1534516841}}

but not work....

**Comment by MongkonEiadon** [comment]
Uhmmmm name should be buyV2

{ “name” : “buyV2”, ....}

**Comment by junghojun** [comment]
send message   => {"name":"buyV2","msg":{"price":1,"act":1,"exp":1534519860,"type":"turbo","direction":"call","time":1534519811}}
Dates : 2018-08-18 오전 12:31:00
Dates : 2018-08-18 오전 12:30:11
Server's authentication succeeded ...

it is result...... but not work...

**Comment by junghojun** [comment]
=>  {"name":"user-changed","msg":{"user_id":0,"user":{"id":0,"can_answer":true,"last_answer":-1,"code":"16ecf0b","life_count":0,"total_life_count":1,"host":25589690,"is_watcher":false,"watch_count":0,"referral_awarded":true,"locale":"","nick_name":"","name":"liau wei jiet","avatar":"https://files.iqoption.com/storage/public/59/f2/bd13b54e4.jpeg","quiz":0,"points":0,"game_points":0,"country_id":119}}}
    =>  {"name":"user-changed","msg":{"user_id":0,"user":{"id":0,"can_answer":true,"last_answer":-1,"code":"16ecf0b","life_count":0,"total_life_count":1,"host":25589690,"is_watcher":false,"watch_count":0,"referral_awarded":true,"locale":"","nick_name":"","name":"liau wei jiet","avatar":"https://files.iqoption.com/storage/public/59/f2/bd13b54e4.jpeg","quiz":0,"points":0,"game_points":0,"country_id":119}}}
    =>  {"name":"user-changed","msg":{"user_id":0,"user":{"id":0,"can_answer":true,"last_answer":-1,"code":"18677ba","life_count":2,"total_life_count":3,"host":24039179,"is_watcher":false,"watch_count":0,"referral_awarded":true,"locale":"","nick_name":"","name":"Teo Chui Lai","avatar":"","quiz":0,"points":0,"game_points":0,"country_id":175}}}
    =>  {"name":"user-changed","msg":{"user_id":0,"user":{"id":0,"can_answer":true,"last_answer":-1,"code":"18677ba","life_count":2,"total_life_count":3,"host":24039179,"is_watcher":false,"watch_count":0,"referral_awarded":true,"locale":"","nick_name":"","name":"Teo Chui Lai","avatar":"","quiz":0,"points":0,"game_points":0,"country_id":175}}}

new result i have... but it is work?;

**Comment by MongkonEiadon** [comment]
Did you send on secured connection? Before you open position you need to send the “ssid ” message to make secured channel

**Comment by junghojun** [comment]
yes realdy connect and sending. but not work...

**Comment by junghojun** [comment]
logged in success!
send message   => {"name":"ssid","msg":"130bb52454ff801a6ef5b1644245e175"}
Server's authentication succeeded ...

Server's authentication succeeded ...

Server's authentication succeeded ...

Server's authentication succeeded ...

Server's authentication succeeded ...

Connect Success
now : 2018-08-18 오전 3:43:16
expiration : 2018-08-18 오전 3:44:00
send message   => {"name":"buyV2","msg":{"price":1,"act":1,"exp":1534531440,"type":"turbo","direction":"call","time":1534531396}}
Server's authentication succeeded ...

**Comment by junghojun** [comment]
what is module of the OpenWebSocketAsync1() function with OpenAsync()?

i use to WebSocket4Net.WebSocket module.. but the module haven't OpenAsync()

Please ask me... the .NetFramework is 4.6.1

**Comment by junghojun** [comment]
i sent this lists.. because the Ssid key need.. it is right?

request.AddHeader("Content-Type", "application/x-www-form-urlencoded");
            request.AddHeader("content-type", "multipart/form-data");
            request.AddHeader("Accept", "application/json");
            request.AddParameter("email", "emails", ParameterType.QueryString);
            request.AddParameter("password", "password", ParameterType.QueryString);




            // execute the request
            IRestResponse response = client.Execute(request);

**Comment by junghojun** [comment]
it is my  connect and trading souce..

something Is there something wrong?

 var client = new RestClient("https://auth.iqoption.com/api/v1.0/login");
            var request = new RestRequest(Method.POST);







            // easily add HTTP Headers
            request.AddHeader("Content-Type", "application/x-www-form-urlencoded");
            request.AddHeader("content-type", "multipart/form-data");
            request.AddHeader("Accept", "application/json");
            request.AddParameter("email", "wjdwlxo11@naver.com", ParameterType.QueryString);
            request.AddParameter("password", "q9635252", ParameterType.QueryString);




            // execute the request
            IRestResponse response = client.Execute(request);





            var content = response.Content; // raw content as string

            var result = response.Content.JsonAs<IqHttpResult<SsidResultMessage>>();
            result.IsSuccessful = true;

            SecuredToken = result.Data;
            
            if (SecuredToken != null)
            {
                Console.WriteLine("datas :::::::::::" + SecuredToken.Ssid.ToString());
           
                screetKey = SecuredToken.Ssid.ToString();
                
            }
            else
            {
                Console.WriteLine("login is failed");
            }

            RunSample();




  public async Task RunSample()
        {
          

            

                IqOptionApi api = new IqOptionApi("email", "password",this.SecuredToken.Ssid);

                Console.WriteLine("SecuredToken.Ssid : " + this.SecuredToken.Ssid);

           
            if (await api.ConnectAsync())
                {
                    Console.WriteLine("Connect Success");
                    
                    //get profile
                    var profile = await api.GetProfileAsync();

                    //profile.BalanceId

                    long BalenceTypesReal =0;
                    long BalenceTypesDemo =0;
                    long BalenceTypestonerment = 0;



                    profile.BalanceType = 1;
                    profile.BalanceType = 2;
                    profile.BalanceType = 4;



                    if (profile.BalanceType == 2)
                    {
                     
                        BalenceTypestonerment = profile.BalanceId;
                    }
                    else if (profile.BalanceType == 4)
                    {
                       
                        BalenceTypesDemo = profile.BalanceId;
                    }
                    else if(profile.BalanceType == 1)
                    {
                      
                        BalenceTypesReal = profile.BalanceId;
                    }

                    

          
                   


                

                    var test22 = await api.ChangeBalanceAsync(BalenceTypesDemo);


                    

                    var exp = DateTime.Now.AddMinutes(0);
                    var exp1 = DateTime.Now.AddMinutes(0);
-
             
                    api.BuyAsync("buyV2", ActivePair.EURUSD, 1, OrderDirection.Call, exp); // the times change in Websocket File for realtime server datas.
                



                    Console.WriteLine("herere");



                }
            




        }

**Comment by junghojun** [comment]
just print of the results...

try
datas :::::::::::3364cfd57411c4bae10df12b2b15d4d8
here1
send message   => {"name":"ssid","msg":"3364cfd57411c4bae10df12b2b15d4d8"}
SecuredToken.Ssid : 3364cfd57411c4bae10df12b2b15d4d8
done
send message   => {"name":"ssid","msg":"5d99067b6d149f1ba34622ffa7708972"}
ssid results : 5d99067b6d149f1ba34622ffa7708972
Server's authentication succeeded ...

Connect Success
Expiration :2018-08-18 오전 8:12:00 +09:00
Time :2018-08-18 오전 8:10:42 +09:00
send message   => {"name":"buyV2","msg":{"price":1,"act":76,"exp":1534547520,"type":"turbo","direction":"call","time":1534547442}}
    =>  {"name":"buyV2_result","msg":{"isSuccessful":false,"message":"user not authorized","result":null}}

**Comment by junghojun** [comment]
how to send the profile?

**Comment by MongkonEiadon** [comment]
Nice , the candles feature I didn’t implement yet, but still working in progress

**Comment by MongkonEiadon** [comment]
Now you can use get candles feature 

``` javascript
var candles = await api.GetCandlesAsync(ActivePair.EURUSD, 1, 100, DateTimeOffset.Now);
```

**Comment by excepticons** [comment]
How I can select practice or real account before open a order?
