### ISSUE TITLE
BuyAsing Not Working At All Version!

### ISSUE THREAD

**Issue by pubruck** [MongkonEiadon/IqOption.Net#32]
i have tried with BuyAsying bro,  but it's not responding. even if i use your new version of api, its not working. but some time trade was placed. i have tried up to 100 times, so unfortunately just 2 trades was placed via BuyAsync. i am thinking something went wrong with iqoption changes ,  i can see and get the profile information well. so it's working well. but it,s only not responding. i hope you will solve the problem. thank you bro,

**Comment by fabriciomarti** [comment]
I too have same problem.... help man, please

**Comment by fabriciomarti** [comment]
today work for me

**Comment by pubruck** [comment]
are you sure that is working well now bro ???  if it working well i will be happy with it. thank you !

**Comment by FabioAlbano** [comment]
Same problem, I can connect and get the profile but BuyAsync doesn't work.

**Comment by pubruck** [comment]
i am thinking issue with websocket bro,  http api is working well.  but websocket is an issue,

**Comment by dolonfly** [comment]
me too, can  get profile information, but BuyAsying not work

**Comment by lucaspoliveira** [comment]
This is working right now?

**Comment by pubruck** [comment]
no it,s working for me, i am thinking might be install other websocket .

**Comment by kiranmaya** [comment]
anybody solved this?

**Comment by lucaspoliveira** [comment]
@kiranmaya , i belive that no. 

Anybody knows some API for .NET ?

**Comment by fabriciomarti** [comment]
> anybody solved this?

Worked fine for me.

**Comment by lucaspoliveira** [comment]
> > anybody solved this?
> 
> Worked fine for me.

The current version ?

**Comment by fabriciomarti** [comment]
> > > anybody solved this?
> > 
> > 
> > Worked fine for me.
> 
> The current version ?

yes.... I think the problem is the service on IQ Option, temporary and region.

**Comment by kiranmaya** [comment]
There is un- commited alpha version ,is that version working ?

**Comment by kiranmaya** [comment]
> > > > anybody solved this?
> > > 
> > > 
> > > Worked fine for me.
> > 
> > 
> > The current version ?
> 
> yes.... I think the problem is the service on IQ Option, temporary and region.
from which region you will able to put buy order . we can try that region with proxies .

**Comment by pubruck** [comment]
i am using python now, its working well, OTC working well..

**Comment by lucaspoliveira** [comment]
> i am using python now, its working well, OTC working well..

Can you share the link ?

**Comment by kiranmaya** [comment]
> C
plz share repo url .

**Comment by MightyMaxSaviorOfTheUniverse** [comment]
Hello, 

I see since the second of December this year Iqoption has changed the buy request into a XHR request.

I've managed to communicate with this new format setup with the below code, but now there is a formatting issue I was hoping some genius could resolve. 

Any one smart enough to handle the error exception that keeps getting thrown up

**b'{"code":400,"errors":"Invalid value of X-Action header. Allowed values: \\"single\\", \\"bulk\\""}'**

```url = 'https://event.iqoption.com/api/v1/events'
headers = [  {'Host': 'event.iqoption.com'},
             {'Connection': 'keep-alive'},
             {'Content-Length': '1191'},
             {'X-Action': 'bulk'},
             {'Origin': 'https://iqoption.com'},
             {'User-Agent': 'ozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML}, like Gecko) Chrome/57.0.0.12335 Safari/537.36'},
             {'Content-Type': 'application/json'},
             {'Accept': '*/*'},
             {'DNT': '1'},
             {'Referer': 'https://iqoption.com/traderoom'},
             {'Accept-Encoding': 'gzip}, deflate}, br'},
             {'Accept-Language': 'en-GB},en-US;q=0.8},en;q=0.6'},
             {}
            ]
body = {'category':'button_pressed',
             'name':'traderoom_deal-call',
             'value':'1',
             'user_id':'My User ID Not Sharing',
             'group_id':'195',
             'platform_id':'9',
             'app_version':'1632.5.2413.release',
             'device_id':'MyID Im Not SHARING THIS',
             'time':'11',
             'parameters':[{
                 'asset_id':'2',
                 'balance_type':'4',
                 'expiration_time':'111',
                 'instrument_type':'turbo',
                 'leverage_value':'1',
                 'order_type':'market'
                 }]}
    r = requests.post(url, data=body, headers=headers)
    print(r.content)
    e=e+1
print(r.content)```

**Comment by MightyMaxSaviorOfTheUniverse** [comment]
Well I found out how to replicate the Http Iqotions trading rooms result, the problem is that it doesn't place a bet which probably means there is some other mechanism that is required for trading

I'm totally out of ideas so I'm leaving it up to you guys to brain storm a solution

Replication of the trade room results;
```
body="[{\"category\":\"button_pressed\",\"name\":\"traderoom_deal-call\",\"value\":341.0,\"user_id\":4******9,\"group_id\":195,\"platform_id\":9,\"app_version\":\"1632.5.2413.release\",\"device_id\":\"2********5\",\"time\":1575886437787,\"parameters\":{\"asset_id\":\"6\",\"balance_type\":\"4\",\"expiration_time\":\"1575886500\",\"instrument_type\":\"digital-option\",\"leverage_value\":\"1\",\"order_type\":\"market\",\"spot_strike\":\"1\"}}]"

headers = {  'Host': 'event.iqoption.com',
             'Connection': 'keep-alive',
             'Content-Length': '1191',
             'X-Action': 'bulk',
             'Origin': 'https://iqoption.com',
             'User-Agent': 'ozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML}, like Gecko) Chrome/57.0.0.12335 Safari/537.36',
             'Content-Type': 'application/json',
             'Accept': '*/*',
             'DNT': '1',
             'Referer': 'https://iqoption.com/traderoom',
             'Accept-Encoding': 'gzip}, deflate}, br',
             'Accept-Language': 'en-GB},en-US;q=0.8},en;q=0.6',
            }
url = 'https://event.iqoption.com/api/v1/events'
r = requests.post(url, data=body, headers=headers)
print(r.content)

>>> Result: b'[{"code":200,"errors":[]}]' (This means the bet was successfully bet only nothing happens as far as actually trade results show)

This probably means that the Java Script runs the execution of buying or some other medium, I'm unsure. I'm just going to use my prediction program to continue to make money until you guys find the solution.

If I had enough money I would just pay someone... fuck it I don't have enough bloody money!

**Comment by MightyMaxSaviorOfTheUniverse** [comment]
It is good to know I'm not the only one working on this project

https://github.com/n1nj4z33/iqoptionapi/issues/23#issuecomment-565707288

**Comment by MongkonEiadon** [comment]
I've update now you can OpenOption on master branch

**Comment by MongkonEiadon** [comment]
Buy async now working on version since '2.1.0'
