### ISSUE TITLE
GetCandlesAsync Not Working

### ISSUE THREAD

**Issue by fabriciomarti** [MongkonEiadon/IqOption.Net#33]
The method GetCandlesAsync stop working today for me. He has working well, and suddenly, stop. All the other methods working fine ConnectAsync, BuyAsync, GetProfileAsync, but the GetCandlesAsync no. @MongkonEiadon Help me please!!!!

**Comment by fabriciomarti** [comment]
# #

**Comment by fabriciomarti** [comment]
Return. Stay 2 hours off.

**Comment by eulerbritto** [comment]
Hi, Fabrício.
How até tou doing?
Could you send me an example showing how you use the buyasync method?
TKS.

Em ter, 24 de set de 2019 14:25, fabriciomarti <notifications@github.com>
escreveu:
