### ISSUE TITLE
Please help-me!

### ISSUE THREAD

**Issue by RKDEVSYS** [MongkonEiadon/IqOption.Net#35]
Olá, queria pedir sua ajuda, pois não estou conseguindo comprar uma operação com esta API.
Agradeço desde já

**Comment by MongkonEiadon** [comment]
Could you please tell me in English please, or you can join my gitter [![Gitter](https://badges.gitter.im/Iqoption-Net/community.svg)](https://gitter.im/Iqoption-Net/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)
