### ISSUE TITLE
Works in Console APP,but not in WinForms App

### ISSUE THREAD

**Issue by peterdias** [MongkonEiadon/IqOption.Net#39]
Hello, 

i have just tried the api in VS2017 by creating a windows console app, and it works fine. 
But when i create a project with Windows Form , api doesnt work. it gets hung on ConnectAsync 

No error comes, very strange, What could be the problem ?

**Comment by mndflr** [comment]
@peterdias , any luck with WinForms?
Have you received realtime price data?

**Comment by MongkonEiadon** [comment]
Which you use the .NET Framework, I used on dotnet core base, so sad to tell you i've use Mac to dev this source code, and not sure the winform can run compatible .Net core 3.1? I'll check

**Comment by MongkonEiadon** [comment]
I've checked it support WinForm but you need to upgrade your own .Net Framework following this
![image](https://user-images.githubusercontent.com/3174809/81490516-5d44aa00-92ad-11ea-87f9-94a4dfd23fff.png)
