### ISSUE TITLE
Can't get candles or realtime data..

### ISSUE THREAD

**Issue by mndflr** [MongkonEiadon/IqOption.Net#40]
@MongkonEiadon , Hi, mate! i can get profile data and open order with this. but sample code holds after GetCandlesAsync or SubscribeRealtimeDataAsync. 
How can i get realtime price's?

thanks.

**Comment by danielleitao-sawluz** [comment]
I'm facing the same situation, any help ?

**Comment by ROMAN5** [comment]
Same issue here (version 2.0.2). Real-time price is not working. The closed price from GetCandlesAsync works fine.

**Comment by MongkonEiadon** [comment]
I've fixed now you can follow the example
https://github.com/MongkonEiadon/IqOption.Net/blob/master/sample/IqOptionApi.Samples/SampleRunners/SubscribeRealtimeCandlesSample.cs
