### ISSUE TITLE
buyasync result issue..

### ISSUE THREAD

**Issue by mndflr** [MongkonEiadon/IqOption.Net#41]
Hi, Mate! Thanks a lot for your fixes in 2.0.3.
I've found one more problem..
When we are calling 
` var res = await api.BuyAsync(...`
then BuyResult type should be filled to res variable, but it is not...
so next code is not working completely correct:

```
var res = await api.BuyAsync(ActivePair.EURUSD_OTC, 1, OrderDirection.Call, DateTime.Now.AddMinutes(1));
  _logger.Information(res.Created + "\t" + res.Direction + "\t" + res.ErrorMessage.ToString());
```

logger is not giving any info..
we can see in console that we have msg with name "option" but it is not handled by any method..
![image](https://user-images.githubusercontent.com/64542291/81498605-8d507500-92ce-11ea-9caa-ac5f1bd2e7a9.png)

please fix this... thanks.

**Comment by mndflr** [comment]
oh.. few things more..
please note that timeframes are not matching..
```
var candles = await api.GetCandlesAsync(ActivePair.EURUSD_OTC, TimeFrame.Min60, 100, DateTimeOffset.Now);
_logger.Information($"CandleCollections received {candles.Count}");
foreach(var c in candles.Infos)
{
   _logger.Information(c.From +" \tO=" + c.Open + " \tH=" + c.Max + " \tL=" + c.Min + " \tC=" + c.Close);
}
```
result:
![image](https://user-images.githubusercontent.com/64542291/81499694-fbe50100-92d5-11ea-941e-1d2551d17a0c.png)
not a problem, just notifying.. 

is there any way to work with digital options using this api?

**Comment by MongkonEiadon** [comment]
Nice I'll have a look on this improvement, Thanks a lot

**Comment by danielleitao-sawluz** [comment]
Hi there, got same problem, can't get any return after called buyasync, just the messages that show on logger.

**Comment by Rickjaconero** [comment]
Same problem here

**Comment by MongkonEiadon** [comment]
I've fixed now let me refactor a bit now you can open Digital options also

**Comment by mndflr** [comment]
great!! thanks!!!! digitals is what i really need!
