### ISSUE TITLE
What is the project license?

### ISSUE THREAD

**Issue by rrfaria** [MongkonEiadon/IqOption.Net#46]
Hi I found your project here but I could not identify which license do you use
What is project license ? MIT?

**Comment by evertonhorning** [comment]
hello, cool send me a message ...
I'm a .NET programmer, and I'm making a system for my own use. I have no
intention of selling it.

Em seg, 15 de jun de 2020 19:38, Rafael Far <notifications@github.com>
escreveu:

**Comment by MongkonEiadon** [comment]
I've added MIT License,
