### ISSUE TITLE
Login Demo account

### ISSUE THREAD

**Issue by dewanto** [MongkonEiadon/iqoption.net#6]
Please documentation for login in to demo balance

**Comment by MongkonEiadon** [comment]
In case you login on to www.iqoption.com and use go to tradings with demo account, that account will be set automatically, that mean when you open any position - that position will working on demo account,

or you can change by use this api and use 
``` javascript
api.ChangeBalanceAsync(balanceId: 23423)
```

**Comment by dewanto** [comment]
It's work
Thank you .
