### ISSUE TITLE
api.BuyAsync works once

### ISSUE THREAD

**Issue by eltonnakamura** [MongkonEiadon/IqOption.Net#61]
hello, this BuyAsync works just one time inside the WsClient.TradersMoodObservable().Subscribe 

`                IqClientApi.WsClient.TradersMoodObservable().Subscribe(x =>
                {        
                       var buyResult = IqClientApi.BuyAsync(x.ActivePair, valor, OrderDirection.Call, exp);
                        _logger.Information($"COMPRADO on {x.InstrumentType} - {x.ActivePair} values Higher :{x.Higher}, Lower: {x.Lower}, Dif: ({dif})");
                });
`

after the first i get this error: 
{"request_id":"76","name":"option","msg":{"message":"Time for purchasing options is over, please try again later.","result":{"request_id":null}},"status":4104}

somebody help?!

**Comment by SaDuric** [comment]
Your exp in BuyAsync function has a wrong value.  
I for example use:
await Task.Delay((61 - DateTime.Now.Second)*1000);
var buyResult = IqClientApi.BuyAsync(x.ActivePair, valor, OrderDirection.Call, DateTime.Now);

In other words, I wait for the start of the next minute and then post a buyrequest for the current minute

**Comment by eltonnakamura** [comment]
> You probably use the same exp over and over again. That does not work... you cant buy in the past.
> For example, I use:
> 
> await Task.Delay((61 - DateTime.Now.Second)*1000);
> var buyResult = IqClientApi.BuyAsync(x.ActivePair, valor, OrderDirection.Call, DateTime.Now);
> 
> In other words, I wait for the start of the next minute and then post a buyrequest for the current minute

hummm ok! let's try
