### ISSUE TITLE
Error start iqoption session

### ISSUE THREAD

**Issue by jpr14** [MongkonEiadon/IqOption.Net#67]
Error connecting api IqOptionApiDotNetClient, since yesterday I can't start iqoption session

client = new IqOptionApiDotNetClient(email.Text, password.Text);

if (await client.ConnectAsync())
{

}
else {

}

go directly to else, some solution?

**Comment by fgaldino** [comment]
me too same problem.

**Comment by RodrigoLOliveira** [comment]
no solution yet?

**Comment by denisvyiser** [comment]
I have a solution. (^.^)

You need to Update some classes:

In the  SsidResultMessage class You nedd to update as below:

  `public class SsidResultMessage : IHttpResultMessage
    {
        [JsonProperty("ssid")] public string Ssid { get; set; }

        [JsonProperty("code")] public string Code { get; set; }

        [JsonProperty("message")] public string Message { get; set; }
    }`

And in the IqOptionHttpClient class You need to update LoginAsync as below:

`public Task<IqHttpResult<SsidResultMessage>> LoginAsync()
        {
            var tcs = new TaskCompletionSource<IqHttpResult<SsidResultMessage>>();
            try
            {
                var client = new RestClient("https://auth.iqoption.com/api/v2/login");
                var request = new RestRequest(Method.POST) { RequestFormat = DataFormat.Json }
                    .AddHeader("content-type", "application/json")
                    .AddHeader("Accept", "application/json")
                    .AddJsonBody(new { identifier = LoginModel.Email, password = LoginModel.Password }, "application/json");
                    
                client.ExecuteAsync(request)
                    .ContinueWith(t =>
                    {
                        switch (t.Result.StatusCode)
                        {
                            case HttpStatusCode.OK:
                            {
                                var success = t.Result.Content.JsonAs<SsidResultMessage>();

                                var result = new IqHttpResult<SsidResultMessage>() {Data = success, IsSuccessful = true };

                                SecuredToken = result.Data;

                                Client.CookieContainer = new CookieContainer();
                                Client.CookieContainer.Add(new Cookie("ssid", SecuredToken.Ssid, "/", "iqoption.com"));

                                tcs.TrySetResult(result);
                                break;
                            }
                            default:
                            {
                                var error = t.Result.Content.JsonAs<SsidResultMessage>();
                                var result = new IqHttpResult<SsidResultMessage>() { Data = error, IsSuccessful = true };
                                    
                                tcs.TrySetResult(result);

                                break;
                            }
                        }
                    });
            }
            catch (Exception ex)
            {
                tcs.TrySetException(ex);
            }


            return tcs.Task;
        }`

**Comment by denisvyiser** [comment]
I have a solution. (^.^)

You need to Update some classes:

In the SsidResultMessage class You nedd to update as below:

public class SsidResultMessage : IHttpResultMessage
{
[JsonProperty("ssid")] public string Ssid { get; set; }

    [JsonProperty("code")] public string Code { get; set; }

    [JsonProperty("message")] public string Message { get; set; }
}
And in the IqOptionHttpClient class You need to update LoginAsync as below:

public Task<IqHttpResult> LoginAsync()
{
var tcs = new TaskCompletionSource<IqHttpResult>();
try
{
var client = new RestClient("https://auth.iqoption.com/api/v2/login");
var request = new RestRequest(Method.POST) { RequestFormat = DataFormat.Json }
.AddHeader("content-type", "application/json")
.AddHeader("Accept", "application/json")
.AddJsonBody(new { identifier = LoginModel.Email, password = LoginModel.Password }, "application/json");

            client.ExecuteAsync(request)
                .ContinueWith(t =>
                {
                    switch (t.Result.StatusCode)
                    {
                        case HttpStatusCode.OK:
                        {
                            var success = t.Result.Content.JsonAs<SsidResultMessage>();

                            var result = new IqHttpResult<SsidResultMessage>() {Data = success, IsSuccessful = true };

                            SecuredToken = result.Data;

                            Client.CookieContainer = new CookieContainer();
                            Client.CookieContainer.Add(new Cookie("ssid", SecuredToken.Ssid, "/", "iqoption.com"));

                            tcs.TrySetResult(result);
                            break;
                        }
                        default:
                        {
                            var error = t.Result.Content.JsonAs<SsidResultMessage>();
                            var result = new IqHttpResult<SsidResultMessage>() { Data = error, IsSuccessful = true };
                                
                            tcs.TrySetResult(result);

                            break;
                        }
                    }
                });
        }
        catch (Exception ex)
        {
            tcs.TrySetException(ex);
        }


        return tcs.Task;
    }

**Comment by Anderson-SG** [comment]
@denisvyiser I made the changes you suggested, but still no result, do you know about anything else?
